/**
 * messy-3000.csv, end to end, through the real contacts import pipeline:
 * sniffCsv -> readHeaders -> guessMapping -> runImport, against a real
 * (in-memory) database. No mocks.
 *
 * The fixture (tests/fixtures/messy-3000.csv, generated by
 * tests/fixtures/gen-messy-3000.mjs, documented in tests/fixtures/README.md)
 * is the kind of export a real trade owner hands over on install day: a BOM,
 * CRLF, one full-name column, non-obvious headers, ragged phone formats,
 * exact and near duplicates, blank and comma-only rows, and a currency and a
 * date column in several notations each.
 *
 * Every number below was read off an actual run of this fixture through this
 * code (not assumed), the same way tests/repo/data/import.test.ts and
 * tests/fixtures/README.md verify their own fixtures' numbers.
 */
import { readFileSync, existsSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { afterEach, describe, expect, it } from "vitest";
import { createHarness, type Harness } from "../harness";
import * as contacts from "../../../src/db/repos/contacts";
import * as companies from "../../../src/db/repos/companies";
import { parseCsvText, readHeaders, sniffCsv } from "../../../src/lib/csv";
import { guessMapping, type ColumnMapping } from "../../../src/features/data/lib/mapping";
import { runImport, type ImportResult } from "../../../src/features/data/lib/importRun";

const here = dirname(fileURLToPath(import.meta.url));
const FIXTURE = join(here, "..", "..", "fixtures", "messy-3000.csv");

let h: Harness | null = null;
afterEach(() => {
  h?.dispose();
  h = null;
});

async function importFixture(): Promise<{ result: ImportResult; mapping: ColumnMapping[] }> {
  const bytes = new Uint8Array(readFileSync(FIXTURE));
  const sniff = sniffCsv(bytes);
  const { headers, delimiter } = readHeaders(sniff.text, { delimiter: sniff.delimiter });
  const mapping = guessMapping(headers);
  const result = await runImport({
    text: sniff.text,
    mapping,
    delimiter,
    policy: "skip",
  });
  return { result, mapping };
}

/* -------------------------------------------------------------------------- */
/* the file itself                                                            */
/* -------------------------------------------------------------------------- */

describe("messy-3000.csv: the file", () => {
  it("has a UTF-8 BOM and CRLF line endings throughout", () => {
    const bytes = readFileSync(FIXTURE);
    expect(bytes[0]).toBe(0xef);
    expect(bytes[1]).toBe(0xbb);
    expect(bytes[2]).toBe(0xbf);
    const sniff = sniffCsv(new Uint8Array(bytes));
    expect(sniff.hadBom).toBe(true);
    expect(sniff.newline).toBe("\r\n");
    expect(sniff.delimiter).toBe(",");
  });

  it("parses with zero field-count errors once the BOM is stripped: 2,997 rows reach the importer, not 3,000", () => {
    const bytes = new Uint8Array(readFileSync(FIXTURE));
    const sniff = sniffCsv(bytes);
    // walkCsv (behind readHeaders/runImport) uses skipEmptyLines: "greedy",
    // which the real import path parses with. The 3,000 rows the generator
    // wrote include 3 "just commas" rows with every field blank; greedy mode
    // treats an all-blank row exactly like a blank line and drops it before
    // it ever reaches applyMapping - the same fate as the 4 genuinely empty
    // lines injected separately. No parse error is raised either way: this
    // file never has a ragged row, only rows with nothing in them.
    expect(() => parseCsvText(sniff.text, { delimiter: sniff.delimiter })).not.toThrow();
    const parsed = parseCsvText(sniff.text, { delimiter: sniff.delimiter });
    expect(parsed.rowCount).toBe(2997);
  });

  it("reads a header row of exactly the ten documented, mixed-case column names", () => {
    const bytes = new Uint8Array(readFileSync(FIXTURE));
    const sniff = sniffCsv(bytes);
    const { headers } = readHeaders(sniff.text, { delimiter: sniff.delimiter });
    expect(headers).toEqual([
      "Customer Name",
      "Co.",
      "Cell",
      "E-mail Address",
      "Notes/Comments",
      "City",
      "State",
      "Zip",
      "Total Spent",
      "Last Service Date",
    ]);
  });
});

/* -------------------------------------------------------------------------- */
/* the mapper's guesses                                                       */
/* -------------------------------------------------------------------------- */

describe("messy-3000.csv: what the mapper guesses for every column", () => {
  it("maps the ten non-obvious headers the way a human would, or leaves an out-of-schema column on Skip", async () => {
    const bytes = new Uint8Array(readFileSync(FIXTURE));
    const sniff = sniffCsv(bytes);
    const { headers } = readHeaders(sniff.text, { delimiter: sniff.delimiter });
    const mapping = guessMapping(headers);
    const byHeader = new Map(mapping.map((m) => [m.header, m]));

    // The single full-name column ("Customer Name") and the abbreviated
    // company column ("Co.") are the two guesses this fixture exists to
    // exercise; both were landing on Skip before this task's mapping.ts fix.
    expect(byHeader.get("Customer Name")?.field).toBe("fullName");
    expect(byHeader.get("Co.")?.field).toBe("company");
    expect(byHeader.get("Cell")?.field).toBe("phone");
    expect(byHeader.get("Cell")?.label).toBe("mobile");
    expect(byHeader.get("E-mail Address")?.field).toBe("email");
    expect(byHeader.get("Notes/Comments")?.field).toBe("notes");
    expect(byHeader.get("City")?.field).toBe("city");
    expect(byHeader.get("State")?.field).toBe("state");
    expect(byHeader.get("Zip")?.field).toBe("postal");

    // "Total Spent" and "Last Service Date" have no contacts-schema home:
    // Skip is the correct guess, not a miss - there is nothing to map them to.
    expect(byHeader.get("Total Spent")?.field).toBe("skip");
    expect(byHeader.get("Last Service Date")?.field).toBe("skip");

    // Every guessed column is in fact a guess (nothing here came from a
    // remembered mapping), and nothing at all is left unaccounted for.
    expect(mapping).toHaveLength(10);
    for (const m of mapping) expect(m.guessed).toBe(true);
  });
});

/* -------------------------------------------------------------------------- */
/* the run: exact counts                                                      */
/* -------------------------------------------------------------------------- */

describe("messy-3000.csv: the import run", () => {
  it("reads 2,997 rows (3,000 written rows minus 3 comma-only rows papaparse's greedy skip absorbs, same as the 4 genuinely blank lines)", async () => {
    h = await createHarness();
    const { result } = await importFixture();
    expect(result.totalRows).toBe(2997);
  });

  it("accepts 2,991 rows and skips exactly 6, all six being duplicate emails, and the arithmetic adds up", async () => {
    h = await createHarness();
    const { result } = await importFixture();

    expect(result.created).toBe(2991);
    expect(result.updated).toBe(0);
    expect(result.skipped).toBe(6);
    expect(result.created + result.updated + result.skipped).toBe(result.totalRows);
    expect(result.skippedTruncated).toBe(false);

    // Every one of the 6 skips is a same-email duplicate the file itself
    // contains (two deliberate exact duplicates, one bulk-derived exact
    // duplicate, three near-duplicate pairs) - not a parse failure and not
    // an unfileable row.
    expect(result.skippedRows).toHaveLength(6);
    for (const row of result.skippedRows) {
      expect(row.reason).toMatch(/^Already in Helix \(matched on email /);
    }
    const emails = result.skippedRows.map((r) => r.reason.match(/email (.+)\)\.$/)?.[1]).sort();
    expect(emails).toEqual(
      [
        "adimarco@example.com",
        "brandon.pruitt5@example.com",
        "daniel.whitfield12@example.com",
        "gracew@example.com",
        "k.osei@example.com",
        "melissa.nakamura@example.com",
      ].sort(),
    );
  });

  it("surfaces every warning-level row - not just the unfileable ones - so nothing that imported quietly goes unreported", async () => {
    h = await createHarness();
    const { result } = await importFixture();

    // Before this task's fix, `contactsResultView` hard-coded `warnings: []`
    // and a row that imported successfully but with something Helix had to
    // decide about (an unparseable phone, no name at all) was never recorded
    // anywhere the owner could see.
    expect(result.warnings.length).toBe(61);
    expect(result.warningsTruncated).toBe(false);

    const byKind = new Map<string, number>();
    for (const w of result.warnings) byKind.set(w.kind, (byKind.get(w.kind) ?? 0) + 1);
    expect(byKind.get("phone")).toBe(1);
    expect(byKind.get("name")).toBe(60);

    const phoneWarning = result.warnings.find((w) => w.kind === "phone");
    expect(phoneWarning?.message).toBe(
      '"801.555.CALL" is not a phone number Helix can dial. It will be saved exactly as typed.',
    );
    expect(phoneWarning?.column).toBe("Cell");
  });

  it("takes a real pre-import backup before writing a single row", async () => {
    h = await createHarness();
    const { result } = await importFixture();
    expect(result.preImportBackupPath).not.toBeNull();
    expect(existsSync(result.preImportBackupPath!)).toBe(true);
  });
});

/* -------------------------------------------------------------------------- */
/* spot checks: the specific edge cases the fixture was built to exercise     */
/* -------------------------------------------------------------------------- */

describe("messy-3000.csv: spot checks on the edge cases it was built for", () => {
  it("every required ragged phone shape lands on the right contact, dialable when it can be", async () => {
    h = await createHarness();
    await importFixture();
    const list = await contacts.list({}, { limit: 5000 });

    const cases: { first: string; raw: string; e164: string | null }[] = [
      { first: "Wendy", raw: "801-555-0142 ext 2", e164: "+18015550142" },
      { first: "Marcus", raw: "(385) 555-0199 x14", e164: "+13855550199" },
      { first: "Diane", raw: "801.555.CALL", e164: null },
      { first: "Patrick", raw: "+1 435 555 0117", e164: "+14355550117" },
      { first: "Carla", raw: "8015550188", e164: "+18015550188" },
    ];
    for (const c of cases) {
      const row = list.rows.find((r) => r.firstName === c.first);
      expect(row, `${c.first} was not imported`).toBeDefined();
      const full = await contacts.get(row!.id);
      expect(full?.phones).toHaveLength(1);
      expect(full?.phones[0].raw).toBe(c.raw);
      expect(full?.phones[0].e164).toBe(c.e164);
    }
  });

  it("a row with only a company name imports under the company, with no name and a warning, not a skip", async () => {
    h = await createHarness();
    await importFixture();

    const found = await companies.findByName("Wasatch Front Handyman Co");
    expect(found).not.toBeNull();

    const list = await contacts.list({}, { limit: 5000 });
    const row = list.rows.find((c) => c.companyName === "Wasatch Front Handyman Co");
    expect(row).toBeDefined();
    expect(row?.firstName).toBe("");
    expect(row?.lastName).toBe("");
  });

  it("a company name with an embedded comma and notes with escaped quotes survive the round trip intact", async () => {
    h = await createHarness();
    await importFixture();

    const list = await contacts.list({}, { limit: 5000 });
    const row = list.rows.find((c) => c.firstName === "Priya");
    expect(row).toBeDefined();
    const full = await contacts.get(row!.id);
    expect(full?.companyName).toBe("Chandrasekaran, Reyes & Sons Plumbing");
    expect(full?.notes).toBe(
      'Told us to leave the gate open, "just knock loud" if the dog is barking.',
    );

    const co = await companies.findByName('Bright "The Fence Guys" Fencing');
    expect(co).not.toBeNull();
  });

  it("a non-ASCII name imports untouched", async () => {
    h = await createHarness();
    await importFixture();

    const list = await contacts.list({}, { limit: 5000 });
    const row = list.rows.find((c) => c.firstName === "François");
    expect(row).toBeDefined();
    expect(row?.lastName).toBe("Dubé");
  });

  it("emails with leading/trailing spaces and mixed case are normalized and still dedupe correctly", async () => {
    h = await createHarness();
    await importFixture();

    const list = await contacts.list({}, { limit: 5000 });
    const sarah = list.rows.find((c) => c.firstName === "Sarah" && c.lastName === "Mitchell");
    const bob = list.rows.find((c) => c.firstName === "Bob" && c.lastName === "Larkin");
    expect(sarah).toBeDefined();
    expect(bob).toBeDefined();
    const sarahFull = await contacts.get(sarah!.id);
    const bobFull = await contacts.get(bob!.id);
    expect(sarahFull?.emails.some((e) => e.emailLower === "sarah.mitchell@example.com")).toBe(
      true,
    );
    expect(bobFull?.emails.some((e) => e.emailLower === "bob.larkin@example.com")).toBe(true);
  });

  it("exact duplicates (same row, twice) and near-duplicates (same email, different spelling/phone format) both collapse to one contact under policy 'skip'", async () => {
    h = await createHarness();
    await importFixture();

    const list = await contacts.list({}, { limit: 5000 });

    // Exact duplicate: only one Melissa Nakamura exists.
    const melissas = list.rows.filter((c) => c.firstName === "Melissa" && c.lastName === "Nakamura");
    expect(melissas).toHaveLength(1);

    // Near duplicate: "Katherine Osei" (first occurrence) survives; "Kathy
    // Osei" (the later, same-email row) was skipped rather than creating a
    // second contact.
    const oseis = list.rows.filter((c) => c.lastName === "Osei");
    expect(oseis).toHaveLength(1);
    expect(oseis[0].firstName).toBe("Katherine");
  });
});
